Flurry Android 5.5.0: FlurryAgent Class Reference
FlurryAgent Class Reference
The Flurry Android Analytics Agent allows you to track the usage and behavior of your Android application on users' devices for viewing in the Flurry Analytics system.
Static Public Member Functions
static synchronized void init (Context context, String apiKey)
Initialize the Flurry SDK. Initialize the Flurry SDK.
static void onStartSession (Context context, String apiKey)
static void onStartSession (Context context)
Start or continue a Flurry session for the project on the given Context.
static void onEndSession (Context context)
End a Flurry session for the given Context.
static boolean isSessionActive ()
Check to see if there is an active session.
static String getSessionId ()
Check to see if there is an active session.
SDK Version information
static int getAgentVersion ()
Get the version of the Flurry SDK.
static String getReleaseVersion ()
Get the release version of the Flurry SDK.
Event and Error Logging Methods for reporting custom events and errors during the
session.
static FlurryEventRecordStatus logEvent (String eventId)
Log an event.
static FlurryEventRecordStatus logEvent (String eventId, Map< String, String > parameters)
Log an event with parameters.
static FlurryEventRecordStatus logEvent (String eventId, boolean timed)
Log a timed event.
static FlurryEventRecordStatus logEvent (String eventId, Map< String, String > parameters, boolean timed)
Log a timed event with parameters. Log a timed event with parameters with the Flurry service. To end the timer, call endTimedEvent(String) with this eventId.
static void endTimedEvent (String eventId)
End a timed event.
static void endTimedEvent (String eventId, Map< String, String > parameters)
End a timed event.
static void onError (String errorId, String message, String errorClass)
static void onError (String errorId, String message, Throwable exception)
static void onEvent (String eventId)
static void onEvent (String eventId, Map< String, String > parameters)
Page View Methods Count page views.
static void onPageView ()
Log a page view.
Purchase Logging Methods for logging in-app purchases.
static void setLocationCriteria (Criteria locationCriteria)
Set SKU details.
User Info Methods to set user information.
static void setAge (int age)
Sets the age of the user at the time of this session.
static void setGender (byte gender)
Sets the gender of the user.
static void setUserId (String userId)
Sets the Flurry userId for this session. The Flurry userId can be used to tie a user back to your internal systems. This userId will travel along with any event reporting that the Flurry Dev Portal provides.
Pre-Init Calls - Optional SDK settings that should be called before init.
static void setFlurryAgentListener (FlurryAgentListener listener)
Sets the listener.
static void setLogEnabled (boolean isEnabled)
true to enable or false to disable the internal logging for the Flurry SDK.
static void setLogLevel (int logLevel)
Set the log level of the internal Flurry SDK logging.
static void setVersionName (String versionName)
Set the version name of the app. Set the name of the this version of the app. This name will appear in the http://dev.flurry.com as a filtering option by version for many charts.
static void setReportLocation (boolean reportLocation)
Set whether Flurry should record location via GPS. Defaults to true.
static void setLocation (float lat, float lon)
Set the default location. Useful when it is necessary to test analytics from other countries or places, or if your app is location-aware and you do not wish the Flurry SDK to determine the user location via GPS.
static void clearLocation ()
Clear the default location.
static void setContinueSessionMillis (long millis)
Set the timeout for expiring a Flurry session.
static void setLogEvents (boolean logEvents)
true to enable event logging or false to disable event logging.
static void setCaptureUncaughtExceptions (boolean isEnabled)
true to enable or false to disable the ability to catch all uncaught exceptions and have them reported back to Flurry.
static void addOrigin (String originName, String originVersion)
Add origin attribution.
static void addOrigin (String originName, String originVersion, Map< String, String > originParameters)
Add origin attribution with parameters.
static void setPulseEnabled (boolean isEnabled)
true to enable or false to disable Flurry Pulse.
Detailed Description
The Flurry Android Analytics Agent allows you to track the usage and behavior of your Android application on users' devices for viewing in the Flurry Analytics system.
Author
2009-2014 Flurry, Inc. All Rights Reserved
Set of methods that allow developers to capture detailed, aggregate information regarding the use of their app by end users.
See Also
Flurry Publisher Support Site for more information
Member Function Documentation
static void addOrigin (String originName, String originVersion) static
Add origin attribution.
 FlurryAgent.addOrigin("An Origin without Params", "Origin Version");
*
Note
Only 10 unique originNames can be logged with the Flurry service per project.
Parameters
originName The name/id of the origin you wish to attribute.
originVersion The version of the origin you wish to attribute.
See Also
For a parameterized version: addOrigin(String, String, Map< String, String >)
static void addOrigin (String originName, String originVersion, Map< String, String > originParameters) static
Add origin attribution with parameters.
Since
Add an origin with parameters with the Flurry service. The event is identified by the originName, which is a String. An originVersion, which is a String. A Map<String, String> of parameters can be passed in where the key is the parameter name, and the value is the value.
Note
Only up to 10 parameters can be passed in with the Map.
 // Add an origin with params, where param1=value1 and param2=value2 Map<String, String>
*       params = new HashMap<String, String>(); params.put("param1", "value1");
*       params.put("param2", "value2"); FlurryAgent.addOrigin("An Origin with Params", "Origin Version",
*       params);
*
Parameters
originName The name/id of the origin you wish to attribute.
originVersion The version of the origin you wish to attribute.
parameters A Map<String, String> of the parameters which should be submitted with this origin attribution.
See Also
For more information on origins: addOrigin(String, String)
References FlurryAgent.addOrigin().
static void endTimedEvent (String eventId) static
End a timed event.
See Also
See logEvent(String, boolean) for more details.
Parameters
eventId The name/id of the event to end the timer on.
static void endTimedEvent (String eventId, Map< String, String > parameters) static
End a timed event.
See Also
See logEvent(String, Map< String, String >) for more details on events with parameters.
Note
Only up to 10 unique parameters total can be passed for an event, including those passed when the event was initiated. If more than 10 unique parameters total are passed, all parameter updates passed on this endTimedEvent call will be ignored.
Parameters
eventId The name/id of the event to end the timer on.
parameters A Map<String, String> of parameters to log with this event.
References FlurryAgent.endTimedEvent().
static int getAgentVersion () static
Get the version of the Flurry SDK.
Returns
The version of the Flurry SDK.
static String getReleaseVersion () static
Get the release version of the Flurry SDK.
Returns
The release version GA/Beta of the Flurry SDK with prefix Flurry_Android.
static String getSessionId () static
Check to see if there is an active session.
Since
5.4.0
Note
The session implementation for the Android SDK is implemented as a stack. It is important to match any call to onStartSession(Context, String) in the Android onStart method with a call to onEndSession(Context) in the Android onEnd method. At any point, you can call this method to get the active session id.
Returns
The current session id, or null if no session is currently active.
static synchronized void init (Context context, String apiKey) static
Initialize the Flurry SDK. Initialize the Flurry SDK.
Parameters
context A reference to a android.content.Context object such as an android.app.Activity or an android.app.Service.
apiKey The API key for your application.
static boolean isSessionActive () static
Check to see if there is an active session.
Since
5.0.0
Note
The session implementation for the Android SDK is implemented as a stack. It is important to match any call to onStartSession(Context, String) in the Android onStart method with a call to onEndSession(Context) in the Android onEnd method. At any point, you can call this method to find if there is an active running session.
Returns
true if a session is currently active, false if not.
static FlurryEventRecordStatus logEvent (String eventId) static
Log an event.
Since
Log an event with the Flurry service. The event is identified by the eventId, which is a String. Events will appear in the developer portal after they have been processed by the Flurry service.
 FlurryAgent.logEvent("An Event without Params");
*
Note
Only 300 unique eventIds can be logged with the Flurry service per project.
Parameters
eventId The name/id of the event.
Returns
enum FlurryEventRecordStatus { FlurryEventFailed, FlurryEventRecorded, FlurryEventUniqueCountExceeded, FlurryEventParamsCountExceeded, FlurryEventLogCountExceeded, FlurryEventLoggingDelayed }
See Also
For a parameterized version: logEvent(String, Map< String, String >)
For a timed version: logEvent(String, boolean)
For a timed and parameterized version: logEvent(String, Map< String, String >, boolean)
static FlurryEventRecordStatus logEvent (String eventId, Map< String, String > parameters) static
Log an event with parameters.
Since
Log an event with parameters with the Flurry service. The event is identified by the eventId, which is a String. A Map<String, String> of parameters can be passed in where the key is the parameter name, and the value is the value.
Note
Only up to 10 parameters can be passed in with the Map. If more than 10 parameters are passed, all parameters will be dropped and the event will be logged as if it had no parameters.
 // Log an event with params, where param1=value1 and param2=value2 Map<String, String>
*       params = new HashMap<String, String>(); params.put("param1", "value1");
*       params.put("param2", "value2"); FlurryAgent.logEvent("Event with params", params);
*
Parameters
eventId The name/id of the event.
parameters A Map<String, String> of the parameters which should be submitted with this event.
Returns
enum FlurryEventRecordStatus { FlurryEventFailed, FlurryEventRecorded, FlurryEventUniqueCountExceeded, FlurryEventParamsCountExceeded, FlurryEventLogCountExceeded, FlurryEventLoggingDelayed }
See Also
For more information on events: logEvent(String)
For a timed version: logEvent(String, Map< String, String >, boolean)
References FlurryAgent.logEvent().
static FlurryEventRecordStatus logEvent (String eventId, boolean timed) static
Log a timed event.
Since
1.0
See Also
Log a timed event without parameters with the Flurry service. To end the timer, call endTimedEvent(String) with this eventId.
See logEvent(String) for more details on events.
Parameters
eventId The name/id of the event.
timed True if the event should be timed, false otherwise.
Returns
enum FlurryEventRecordStatus { FlurryEventFailed, FlurryEventRecorded, FlurryEventUniqueCountExceeded, FlurryEventParamsCountExceeded, FlurryEventLogCountExceeded, FlurryEventLoggingDelayed }
References FlurryAgent.logEvent().
static FlurryEventRecordStatus logEvent (String eventId, Map< String, String > parameters, boolean timed) static
Log a timed event with parameters. Log a timed event with parameters with the Flurry service. To end the timer, call endTimedEvent(String) with this eventId.
Note
Only up to 10 parameters can be passed in with the Map. If more than 10 parameters are passed, all parameters will be dropped and the event will be logged as if it had no parameters.
Parameters
eventId The name/id of the event.
parameters A Map<String, String> of parameters to log with this event.
timed True if this event is timed, false otherwise.
Returns
enum FlurryEventRecordStatus { FlurryEventFailed, FlurryEventRecorded, FlurryEventUniqueCountExceeded, FlurryEventParamsCountExceeded, FlurryEventLogCountExceeded, FlurryEventLoggingDelayed }
See Also
See logEvent(String, Map< String, String >) for more details on events with parameters.
References FlurryAgent.logEvent().
static void onEndSession (Context context) static
End a Flurry session for the given Context.
Since
1.0 Pop a session off the stack for this Activity. If no sessions remain after the call to onEndSession(Context) and no new calls to onStartSession(Context, String) are made within the timeout specified (which defaults to 10 seconds) then the session will truly end. Calls to onEndSession should be made from the Activity's onStop method in order to assure a complete analytics lifecycle for the Activity. Please note that if your app only runs on ICS+ (minSdkVersion >= 14) Activity-based sessions will be handled for you automatically. There is no need to call this method unless you wish to track another type of Context.
 // The Activity's onStop method
* @Override protected void onStop() { FlurryAgent.onEndSession(this); }
*
Note
The session implementation for the Android SDK is implemented as a stack. It is important to match any call to onStartSession(Context, String) in the Android onStart method with a call to onEndSession(Context) in the Android onEnd method.
See Also
setContinueSessionMillis(long) for details on setting a custom session timeout.
Parameters
context A reference to a android.content.Context object such as an android.app.Activity or an android.app.Service.
static void onError (String errorId, String message, String errorClass) static
Deprecated:
See #onError(String, String, Throwable)
Parameters
errorId
message
errorClass
static void onEvent (String eventId) static
Deprecated:
See logEvent(String).
Parameters
eventId
static void onEvent (String eventId, Map< String, String > parameters) static
Deprecated:
See logEvent(String, Map < String, String >).
Parameters
eventId
parameters
References FlurryAgent.onEvent().
static void onStartSession (Context context, String apiKey) static
Deprecated:
See onStartSession(Context)
Parameters
context
apiKey
static void onStartSession (Context context) static
Start or continue a Flurry session for the project on the given Context.
Since
1.0 So long as there is any Context that has called onStartSession(Context) but not onEndSession(Context), the session will be continued. Also, if a new Context calls onStartSession(Context) within 10 seconds (the default session timeout length) of the last Context calling onEndSession, then the session will be resumed, instead of a new session being created. Session length, usage frequency, events and errors will continue to be tracked as part of the same session. This ensures that as a user transitions from one Activity to another in your application they will not have a separate session tracked for each Activity, but will have a single session that spans many activities. onStartSession should be called from within the onStart method of the activity in question. The first call to onStartSession will set up the configuration for all later occurring calls to onStartSession. Please note that if your app only runs on ICS+ (minSdkVersion >= 14) Activity-based sessions will be handled for you automatically. There is no need to call this method unless you wish to track another type of Context.
 // The Activity's onStart method
* @Override protected void onStart() { // Start the Flurry session
*           FlurryAgent.onStartSession(this); }
*
Note
You MUST initialize the Flurry SDK via #Flurry.init(String) before calling this method. Also, it is important to match any call to onStartSession(Context) in the Android onStart method with a call to onEndSession(Context) in the Android onEnd method.
See Also
setContinueSessionMillis(long) for details on setting a custom session timeout.
Parameters
context A reference to a android.content.Context object such as an android.app.Activity or an android.app.Service.
References FlurryAgent.onStartSession().
static void setAge (int age) static
Sets the age of the user at the time of this session.
Parameters
age valid values are 0-110
static void setCaptureUncaughtExceptions (boolean isEnabled) static
true to enable or false to disable the ability to catch all uncaught exceptions and have them reported back to Flurry.
Parameters
isEnabled true to enable, false to disable.
static void setContinueSessionMillis (long millis) static
Set the timeout for expiring a Flurry session.
Since
1.0 The default value for a session timeout is 10,000 milliseconds. The minimum timeout for a session is 5,000 milliseconds. Calling onStartSession(Context, String) within the set time will cause the previous session to resume. Calling onStartSession(Context, String) after the set amount of time has passed will result in a new session being created.
Note
This must be called before onStartSession to have an effect.
 FlurryAgent.setContinueSessionMillis(60 * 1000); // Set session timeout to 60 seconds
*       FlurryAgent.onStartSession(this, kApiKey);
*
See Also
onStartSession(Context, String) and onEndSession(Context)
Parameters
millis The time in milliseconds to set the session timeout to. Minimum value of 5000.
static void setFlurryAgentListener (FlurryAgentListener listener) static
Sets the listener.
The listener is an interface which can be implemented to receive notification of various events associated with session.
Parameters
listener Your implementation of the Flurry agent listener.
static void setGender (byte gender) static
Sets the gender of the user.
Parameters
gender One of the values among Constants::MALE, Constants::FEMALE and Constants::UNKNOWN as defined in Constants.
References Constants.UNKNOWN.
static void setLocation (float lat, float lon) static
Set the default location. Useful when it is necessary to test analytics from other countries or places, or if your app is location-aware and you do not wish the Flurry SDK to determine the user location via GPS.
Parameters
lat The latitude
lon The longitude
static void setLocationCriteria (Criteria locationCriteria) static
Set SKU details.
     @since Set up the SKU details with the Flurry service. The SKU details bundle will be returned
            by the Google IAB (In App Billing) API in response to the getSkuDetails() method.
            SKU details are necessary to process purchase events correctly.
 FlurryAgent.setSkuDetails(skuDetails);
//     *
Parameters
skuDetails The SKU details Bundle returned by Google IAB. Log a purchase.
Since
Log an purchase with the Flurry service. The purchase response Intent will be returned by the Google IAB (In App Billing) API when a purchase has been made. Purchases will appear in the developer portal after they have been processed by the Flurry service.
 FlurryAgent.logPurchase(purchaseResponse);
//     *
Parameters
purchaseResponseIntent The purchase response Intent returned by Google IAB.
parameters A Map<String, String> of parameters to log with this event. Log a purchase. TODO: fill in TODO: enums or constants?
Deprecated:
Flurry SDK now uses PASSIVE_PROVIDER to fetch the location information if app has ACCESS_FINE_LOCATION permission.
See Also
setReportLocation for more information.
static void setLogEnabled (boolean isEnabled) static
true to enable or false to disable the internal logging for the Flurry SDK.
Parameters
isEnabled true to enable logging, false to disable it.
static void setLogEvents (boolean logEvents) static
true to enable event logging or false to disable event logging.
Parameters
logEvents true to log events, false to disable event logging.
static void setLogLevel (int logLevel) static
Set the log level of the internal Flurry SDK logging.
Parameters
logLevel The level to set it to.
static void setPulseEnabled (boolean isEnabled) static
true to enable or false to disable Flurry Pulse.
Parameters
isEnabled true to enable, false to disable.
static void setReportLocation (boolean reportLocation) static
Set whether Flurry should record location via GPS. Defaults to true.
Parameters
reportLocation True to allow Flurry to record location via GPS, false otherwise
static void setUserId (String userId) static
Sets the Flurry userId for this session. The Flurry userId can be used to tie a user back to your internal systems. This userId will travel along with any event reporting that the Flurry Dev Portal provides.
Parameters
userId
static void setVersionName (String versionName) static
Set the version name of the app. Set the name of the this version of the app. This name will appear in the http://dev.flurry.com as a filtering option by version for many charts.
Parameters
versionName The version of the app.
The documentation for this class was generated from the following file:
FlurryAgent.java